### ISSUE TITLE
Java API Typo 

### ISSUE THREAD

**Issue by solace-zahratabar** [SolaceSamples/solace-samples-java-new#33]
On java api there is a such strange comments in code:

https://github.com/SolaceSamples/solace-samples-java/blob/25ca3d1964852f4ceda27ccf0e5ff7fb93cfefe2/src/main/java/com/solace/samples/java/patterns/GuaranteedBlockingPublisher.java#L124

publisher.publishAwaitAcknowledgement(message,Topic.of(topicString),2000L);  // wait up to 2 seconds?

**Comment by aaron-613** [comment]
What is strange about it?  The sample was written to wait/block for up to 2 seconds to receive an ACKnowledgement from the broker.  I agree this is a bit long (although not as long as REST request timeouts of 15 or 30 seconds).  The broker could take up to 1 second to reply with an ACK (due to AD window configuration), so maybe 1.2 seconds or so would be a more appropriate number.

Or do you just want a better, more explanatory comment?

**Comment by solace-zahratabar** [comment]
I believe there is a typo in the code. Is "2000L" should be 2000ms ?

**Comment by Mrc0113** [comment]
I'll point out the easy thing - we should remove the  `?` from the end of the comment

**Comment by aaron-613** [comment]
I slightly updated the comments.  Created https://github.com/SolaceSamples/solace-samples-java/pull/35

> _I believe there is a typo in the code. Is "2000L" should be 2000ms ?_

This is not a typo... it is how you specify a `long` value in Java.  The API designer decided to make the milliseconds field a long (instead of an int?), in case you need to block and wait more than 2^31 ms ~ 25 days..!

**Comment by Mrc0113** [comment]
Closing now that this has been resolved in #35
